### ISSUE TITLE
Should we change the default font

### ISSUE THREAD

**Issue by MaanooAk** [CSD-FOSS-Team/genume#32]
@drazioti at his orginal post, he was setting the font to a fixed value. 

Do we want to do the same, or just let the user's theme to decide?

**Comment by drazioti** [comment]
I tried the default font in gtk and it was awful. That why I changed it. I leave it to you, if the selection of fonts will be user's decision or not.

**Comment by Sima214** [comment]
> Close as a **duplicate** of https://stackoverflow.com/a/10916008

I think it would be for the best if we tried to match the user's theme.

**Comment by MaanooAk** [comment]
The font will remain the default user font, as is the normal/expected behavior.
