### ISSUE TITLE
python 3.5 bug

### ISSUE THREAD

**Issue by drazioti** [CSD-FOSS-Team/genume#48]
I supposed that the code is not reviewed for python 3.5 also. Someone can easily repeat this bug by doing the following:
First install miniconda (https://conda.io/docs/user-guide/install/index.html). Then
$conda create -n py3.5 python=3.5 #new conda enviroment
$source activate py3.5                      #activate the enviroment
(py3.5)$conda install -c pkgw/label/superseded gtk3  #install gtk
(py3.5)$conda install -c conda-forge pygobject
(py3.5)$cd [genume directory]
(py3.5)$python -m genume

The error I got : 
Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme

Also, the system crashed after pushing the buttons on the upper right corner

UPDATE: The same for python3.6

**Comment by MaanooAk** [comment]
This will be solved by #52
