### ISSUE TITLE
Glxinfo: command not found errors

### ISSUE THREAD

**Issue by Winner5001** [CSD-FOSS-Team/genume#58]
Δίνει errors όταν κανεις run το genume. Λύνεται με apt-get install mesa-utils.

**Comment by MaanooAk** [comment]
This should be fixed in the script level. Also similar cases where scripts have dependencies should work even when they are missing (without crashing the whole thing)

**Comment by Sima214** [comment]
I have an idea on how to do this together with #53.

**Comment by MaanooAk** [comment]
@Sima214 Take a look at my (first non-generic) approach at [firewall.sh](https://github.com/CSD-FOSS-Team/genume/blob/master/scripts/software/firewall.sh). 

Are you talking about something in the python side of things?

**Comment by MaanooAk** [comment]
Will be fixed by the new protocol, for now is temp fixed at #65
