### ISSUE TITLE
Bottlenecks

### ISSUE THREAD

**Issue by Sima214** [CSD-FOSS-Team/genume#61]
`OpenGL Bas info.sh` is too slow (almost takes one second on my machine).

**Comment by MaanooAk** [comment]
With #65 the opengl scripts (now one script) execute 5 time faster (on my system).

@Sima214 can you check in yours, and also any other script bottlenecks.

**Comment by Sima214** [comment]
Seems fine now.

**Comment by Sima214** [comment]
Well the partition script takes ~450ms on my computer, but I am sure we both know why that is...
