### ISSUE TITLE
xparser.py issue

### ISSUE THREAD

**Issue by lalashkin** [CSD-FOSS-Team/genume#71]
When trying to  build a pulled project with "make", an python error occurs, which is related with **xparser.py** structure. Namely:
```
while len(cmdl) != 0:
    command = cmdl.pop(0)
    level = cmdl.pop(0)
    key = cmdl.pop(0)
```
I guess, the reason is that my machine (*ASUS-X556UQ laptop*) have different structure of files, which genume is trying to read.
See related screenshot.
![image](https://user-images.githubusercontent.com/26904232/51788053-89a4e780-218a-11e9-8847-a4fe58b9b105.png)

I was able to make this work with a small addition. But this is just weird fix, as I see it.

```
while len(cmdl) != 0 and len(cmdl) >= 3:
    command = cmdl.pop(0)
    level = cmdl.pop(0)
    key = cmdl.pop(0)
```

**Comment by Sima214** [comment]
This is a scripts error.
Also registry(including xparser) got refactored(#60), which should resolve these issues.
I am leaving this open, so we can indeed confirm it got fixed.
