### ISSUE TITLE
Last merge broke gui

### ISSUE THREAD

**Issue by drazioti** [CSD-FOSS-Team/genume#73]
After update to the last version of genume, GUI is broken (python3.5). The tabs have vanished. It seems that the last merge (#60) caused the problem.The gui is working until the commit 
 c98a803782e1f1b76a1d0e0a5254d46d8657d0eb.  I dont't know what is wrong but maybe it is a good idea to go back, until you fix it, in order to have a working master.

**Comment by Sima214** [comment]
Can I get logs?

**Comment by drazioti** [comment]
I don't have some specific errors. The gui does not have tabs. Elaborate what logs do you need

**Comment by Sima214** [comment]
genume.log

**Comment by drazioti** [comment]
17:12:05 [INFO|Registry-0] Registry thread is starting up...
17:12:06 [DEBUG|Registry-0] A refresh has been requested.
17:12:06 [INFO|Registry-0] Currently scanning: scripts
17:12:06 [WARNING|Registry-0] Ignoring: PROTOCOL.md
17:12:06 [WARNING|Registry-0] Ignoring: README.md
17:12:06 [INFO|Registry-0] Currently scanning: about
17:12:06 [INFO|Registry-0] Currently scanning: cpu
17:12:06 [INFO|Registry-0] Currently scanning: disks
17:12:06 [INFO|Registry-0] Currently scanning: distribution
17:12:06 [INFO|Registry-0] Currently scanning: gpu
17:12:06 [INFO|Registry-0] Currently scanning: memory
17:12:06 [INFO|Registry-0] Currently scanning: power
17:12:06 [INFO|Registry-0] Currently scanning: software
17:12:06 [DEBUG|Registry-0] Started child "name.sh" with pid 15903
17:12:06 [DEBUG|Registry-0] Started child "name.sh" with pid 15904
17:12:07 [INFO|Registry-0] Child name.sh (15904) has been executed successfully in 674.23 ms!
17:12:07 [DEBUG|Registry-0] Started child "processors.sh" with pid 15923
17:12:08 [INFO|Registry-0] Child processors.sh (15923) has been executed successfully in 1130.03 ms!
17:12:08 [DEBUG|Registry-0] Started child "cdrom.sh" with pid 15952
17:12:08 [INFO|Registry-0] Child cdrom.sh (15952) has been executed successfully in 192.25 ms!
17:12:08 [DEBUG|Registry-0] Started child "disks.sh" with pid 15957
17:12:09 [INFO|Registry-0] Child name.sh (15903) has been executed successfully in 2503.80 ms!
17:12:09 [DEBUG|Registry-0] Started child "partitions.sh" with pid 15965
17:12:09 [INFO|Registry-0] Child disks.sh (15957) has been executed successfully in 1222.87 ms!
17:12:09 [DEBUG|Registry-0] Started child "dist-finder.sh" with pid 16035
17:12:10 [INFO|Registry-0] Child dist-finder.sh (16035) has been executed successfully in 653.98 ms!
17:12:10 [DEBUG|Registry-0] Started child "gpu-name.sh" with pid 16048
17:12:11 [INFO|Registry-0] Child gpu-name.sh (16048) has been executed successfully in 624.60 ms!
17:12:11 [DEBUG|Registry-0] Started child "opengl.sh" with pid 16114
17:12:15 [INFO|Registry-0] Child opengl.sh (16114) has been executed successfully in 4051.65 ms!
17:12:15 [DEBUG|Registry-0] Started child "cache.sh" with pid 16382
17:12:19 [INFO|Registry-0] Child cache.sh (16382) has been executed successfully in 4618.53 ms!
17:12:19 [DEBUG|Registry-0] Started child "ram.sh" with pid 16649
17:12:21 [INFO|Registry-0] Child ram.sh (16649) has been executed successfully in 1461.52 ms!
17:12:21 [DEBUG|Registry-0] Started child "battery.sh" with pid 16720
17:12:22 [INFO|Registry-0] Child battery.sh (16720) has been executed successfully in 660.73 ms!
17:12:22 [DEBUG|Registry-0] Started child "dc.sh" with pid 16781
17:12:22 [INFO|Registry-0] Child dc.sh (16781) has been executed successfully in 711.10 ms!
17:12:22 [DEBUG|Registry-0] Started child "apps.sh" with pid 16794
17:12:53 [INFO|Registry-0] Child apps.sh (16794) has been executed successfully in 31023.41 ms!
17:12:53 [DEBUG|Registry-0] Started child "firewall.sh" with pid 17083

**Comment by Sima214** [comment]
Could you test with only _about/name.sh_ script?

**Comment by drazioti** [comment]
meaning ?

**Comment by drazioti** [comment]
after pressing the refresh button, I got the following
Exception in thread Registry-0:
Traceback (most recent call last):
  File "/home/draziotis/anaconda2/envs/py3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/draziotis/Documents/genume/genume/registry/registry.py", line 114, in run
    self._execute_children(pending_children)
  File "/home/draziotis/Documents/genume/genume/registry/registry.py", line 90, in _execute_children
    elif slot is not None and slot.do_step():
  File "/home/draziotis/Documents/genume/genume/registry/child.py", line 73, in do_step
    reply = parse_func(command_stack, self.shadow, self.observer, self.state)
  File "/home/draziotis/Documents/genume/genume/registry/parser.py", line 53, in parse_conf
    elif find_executable(e) is None:
  File "/home/draziotis/Documents/genume/genume/utils.py", line 39, in find_executable
    if name in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm/java-8-oracle/db/bin'

**Comment by Sima214** [comment]
I am trying to figure out which parts fails.
Is the output from the scripts delivered?
Are the categories getting merged correctly?
Is the result getting delivered to the main thread correctly?
Is the gui cleared and updated with the new state?

**Comment by drazioti** [comment]
the problem is that you can't reproduce it. Did you change anything to the gui part?

**Comment by Sima214** [comment]
The gui is not deleted and reconstructed for every refresh now. Only the buttons and pages are removed and regenerated.

**Comment by Sima214** [comment]
Also to note the script execution seems to take ∞ time on the log you posted and the gui will stay blank until the first refresh is finished.

**Comment by drazioti** [comment]
It seems  something is going wrong when you call refresh with your script.

**Comment by Sima214** [comment]
>FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm/java-8-oracle/db/bin'

The registry update thread crashed because it could find a directory included in your system path.

**Comment by drazioti** [comment]
This is after the merge. Before was working fine

**Comment by Sima214** [comment]
I think I got it.

**Comment by Sima214** [comment]
Also:
How much time did the gui take to start before the new registry?
What kind of ram and cpu do you have?
If you don't mind could you find a good balance for SCRIPTS_MAX_MULTI_DISPATCH in _genume/constants.py_?

**Comment by drazioti** [comment]
ram 2gb, cpu an old celeorn N2810. But I can't see what genume has to do with my ram and cpu!

**Comment by Sima214** [comment]
A fix is available in the dev branch in the current repository.

**Comment by drazioti** [comment]
what was wrong? After some time (about 30 second) the tabs appeared!

**Comment by Sima214** [comment]
> Elaborate for the third question

'Multithreading' is implemented by starting up multiple scripts at the same time and then round-robin between them. If the numbers of maximum scripts to start at the same time(SCRIPTS_MAX_MULTI_DISPATCH) is too low then the refresh is going to slow. Too high and I could effectively bomb the system.

> what was wrong?

Your PATH contains a directory (**_/usr/lib/jvm/java-8-oracle/db/bin_**) which does not exist.

> ufw may not be installed!

That's a feature. A new command which checks if a certain program is available.

**Comment by drazioti** [comment]
I did not remove from my path the directory .../db/bin, but genume now plays

**Comment by xlxs4** [comment]
The **refresh button** "switches" the current tab to the **about** one:
![2019-02-23-193332_1600x900_scrot](https://user-images.githubusercontent.com/44295592/53289688-dab3f580-37a1-11e9-8800-39b826fb61c0.png)

**Comment by xlxs4** [comment]
I don't understand how it can possibly be slower than the previous version though @drazioti.
Are you sure?

**Comment by drazioti** [comment]
I don't know why, the refresh button "is not faster" than the previous.

**Comment by xlxs4** [comment]
I'll try get a benchmarks table for my rigs when I find the time.

**Comment by drazioti** [comment]
usefull info

**Comment by Sima214** [comment]
Is there any way I can solve the scheduling problem without having information about how much each job requires? Either way the total refresh time cannot be shorter that the longest script, so nothing I can do about that.

**Comment by drazioti** [comment]
What did you improve in the "new" genume?

**Comment by Sima214** [comment]
1. The ui does not freeze.
2. Less picky protocol.
3. Execution of multiple scripts together, but the parsing (thanks to the GIL) still happens in one thread.
4. Higher level api: bash helpers! Probably why everything slowed down.

**Comment by drazioti** [comment]
For case 3. The execution occurs when you call refresh, right? 
Elaborate on 4.

**Comment by Sima214** [comment]
About 4: instead of calling echo(previous version), now you can call from bash (transparently) special python scripts which convert their arguments to commands that the registry can parse.

About 3: Kind of. First we change threads, then _scan_ahead scans the directory structure and finally _execute_children does the execution.

**Comment by Sima214** [comment]
GIL killed of any hope I had about python.

**Comment by drazioti** [comment]
+1 for "About 4: instead of calling echo(previous version), now you can call from bash (transparently) special python scripts which convert their arguments to commands that the registry can parse."

When I play with  parallel programming I prefer cython & openmp instead of multithrading.

**Comment by Sima214** [comment]
@xlxs4 I cannot fix the button.

**Comment by xlxs4** [comment]
@Sima214 I'll check it tomorrow, see if I can help.

**Comment by drazioti** [comment]
Close the ticket
