### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by drazioti** [CSD-FOSS-Team/genume#85]
After
18:58:45 [INFO|Registry-0] Child disks.sh (29937) has been executed successfully in 1269.88 ms!
I got
bla bla
FileNotFoundError: [Errno 2] No such file or directory: '/.../genume/genume/../scripts/graphical_environment/wm.sh': '../genume/genume/../scripts/graphical_environment/wm.sh'

**Comment by Sima214** [comment]
Is the underscore causing it?

**Comment by xlxs4** [comment]
@drazioti @Sima214 It runs successfully on my end, I can't think how the underscore might be related to this.
On a side note, aren't dashes instead of underscores better for file names?

Seems more like a messy installation to me, for whatever reason.

**Comment by xlxs4** [comment]
@drazioti @Sima214 It runs successfully on my end.
I can't imagine how the underscore might be involved in this.
Since that subdir's name is the largest one (?), is there any crazy way you've gone past the 4096 characters kernel PATH limitation?
Maybe a thread [screwed](https://github.com/dask/dask/issues/2656#issuecomment-343903868) up?
Maybe something about rel vs abs path?
Are you running the module from where you should be?

**Comment by xlxs4** [comment]
@drazioti Can you try getting genume from the `dev` branch and see whether the problem persists?

**Comment by Sima214** [comment]
Also more logs!

**Comment by drazioti** [comment]
> @drazioti @Sima214 It runs successfully on my end.
> I can't imagine how the underscore might be involved in this.
> Since that subdir's name is the largest one (?), is there any crazy way you've gone past the 4096 characters kernel PATH limitation?
> Maybe a thread [screwed](https://github.com/dask/dask/issues/2656#issuecomment-343903868) up?
> Maybe something about rel vs abs path?
> Are you running the module from where you should be?



> @drazioti @Sima214 It runs successfully on my end.
Sure. But not in my case
> I can't imagine how the underscore might be involved in this.
> Since that subdir's name is the largest one (?), is there any crazy way you've gone past the 4096 characters kernel PATH limitation?
> Maybe a thread [screwed](https://github.com/dask/dask/issues/2656#issuecomment-343903868) up?
I don't think so
> Maybe something about rel vs abs path?
elaborate
> Are you running the module from where you should be?
nop

**Comment by drazioti** [comment]
the problem appears after
commit 18ceb41a3b6b14cde30546e08bb25c05309550c5
Merge: aebe4e8 168c495
Author: Anastasios Simeonidis <anastasios2014@gmail.com>
Date:   Tue Mar 12 13:28:39 2019 +0200

    Merge pull request #67 from damavrom/master

**Comment by Sima214** [comment]
Yes, I know, bisecting won't find us anything new.
Please confirm the following or provide a full log:
1. where does the exception get generated from?
2. If you copy paste the path provided by the exception/error into a terminal and [**cat**](https://en.wikipedia.org/wiki/Cat_\(Unix\)) it, is it able to find the file?

This is probably me making assumptions when generating [child](https://github.com/CSD-FOSS-Team/genume/blob/master/genume/registry/child.py) [paths](https://docs.python.org/3/library/pathlib.html) in the [registry](https://github.com/CSD-FOSS-Team/genume/blob/master/genume/registry/registry.py) about filesystem capabilities.

I need to find what assumption I made.

**Comment by drazioti** [comment]
the full log
Traceback (most recent call last):
  File "/home/kdraziotis/anaconda3/envs/py3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/kdraziotis/Documents/genume/genume/registry/registry.py", line 114, in run
    self._execute_children(pending_children)
  File "/home/kdraziotis/Documents/genume/genume/registry/registry.py", line 93, in _execute_children
    executing[i] = pending.popleft().start()
  File "/home/kdraziotis/Documents/genume/genume/registry/child.py", line 39, in start
    stdin=sbpr.PIPE, stdout=sbpr.PIPE, close_fds=False, env=self.generate_env())
  File "/home/kdraziotis/anaconda3/envs/py3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/kdraziotis/anaconda3/envs/py3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kdraziotis/Documents/genume/genume/../scripts/graphical_environment/wm.sh': '/home/kdraziotis/Documents/genume/genume/../scripts/graphical_environment/wm.sh'

**Comment by Sima214** [comment]
> and yes, cat finds the file.

Oh no.
Sorry but I have no idea why that one is special.

**Comment by xlxs4** [comment]
@Sima214 Is there any chance err 2 gets raised when it shouldn't?

**Comment by xlxs4** [comment]
@Sima214 Also it'd probably be a good idea to add the 'Help Wanted' tag.

**Comment by Sima214** [comment]
@drazioti you are the only one with this problem.
No one else can reproduce it.

**Comment by MaanooAk** [comment]
https://github.com/CSD-FOSS-Team/genume/commit/b2f166fb8389ffbb7fdcf6a49e4d28431f3dbef4 Fixed it (it was the path of the hashbang inside the file, not the actual path of the file)

**Comment by drazioti** [comment]
WOW. Thank you!
